name: on-pr

on:
  pull_request:
    types:
      - labeled
      - opened
      - reopened
      - synchronize
    paths:
      - '.github/workflows/on-pr.yaml'
      - '.gitops/**'
      - 'apis/**'
      - 'examples/**'
      - 'tests/**'
      - 'functions/**'
      - 'upbound.yaml'

permissions:
  packages: write
  contents: write
  issues: write
  pull-requests: write

jobs:
  validate:
    uses: unbounded-tech/workflows-crossplane/.github/workflows/validate.yaml@v2.5.1
    with:
      examples: |
        [
          { "example": "examples/ipams/minimal.yaml" },
          { "example": "examples/ipams/multi-region.yaml" },
          { "example": "examples/ipams/private-ipv6.yaml" },
          { "example": "examples/ipams/private-ipv6.yaml", "observed_resources": "examples/test/mocks/observed-resources/private-ipv6/steps/1" },
          { "example": "examples/ipams/private-ipv6.yaml", "observed_resources": "examples/test/mocks/observed-resources/private-ipv6/steps/2" },
          { "example": "examples/ipams/private-ipv6.yaml", "observed_resources": "examples/test/mocks/observed-resources/private-ipv6/steps/3" },
          { "example": "examples/ipams/with-subnet-pool.yaml" },
          { "example": "examples/ipams/with-subnet-pool.yaml", "observed_resources": "examples/test/mocks/observed-resources/with-subnet-pool/steps/1" },
          { "example": "examples/ipams/with-subnet-pool.yaml", "observed_resources": "examples/test/mocks/observed-resources/with-subnet-pool/steps/2" },
          { "example": "examples/ipams/with-subnet-pool.yaml", "observed_resources": "examples/test/mocks/observed-resources/with-subnet-pool/steps/3" },
          { "example": "examples/ipams/with-auto-subnet-pool.yaml" },
          { "example": "examples/ipams/with-auto-subnet-pool.yaml", "observed_resources": "examples/test/mocks/observed-resources/with-auto-subnet-pool/steps/1" },
          { "example": "examples/ipams/with-auto-subnet-pool.yaml", "observed_resources": "examples/test/mocks/observed-resources/with-auto-subnet-pool/steps/2" },
          { "example": "examples/ipams/with-auto-subnet-pool.yaml", "observed_resources": "examples/test/mocks/observed-resources/with-auto-subnet-pool/steps/3" },
          { "example": "examples/ipams/with-subnet-pools.yaml" },
          { "example": "examples/ipams/with-subnet-pools.yaml", "observed_resources": "examples/test/mocks/observed-resources/with-subnet-pools/steps/1" },
          { "example": "examples/ipams/with-subnet-pools.yaml", "observed_resources": "examples/test/mocks/observed-resources/with-subnet-pools/steps/2" },
          { "example": "examples/ipams/with-subnet-pools.yaml", "observed_resources": "examples/test/mocks/observed-resources/with-subnet-pools/steps/3" }
        ]
      api_path: apis/ipams
      error_on_missing_schemas: true

  test:
    uses: unbounded-tech/workflows-crossplane/.github/workflows/test.yaml@v2.5.1

  e2e:
    uses: unbounded-tech/workflows-crossplane/.github/workflows/e2e.yaml@v2.5.1
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    with:
      aws: true
      cleanup-timeout-minutes: 20
      timeout-minutes: 30
      debug-example-path: examples/ipams/minimal.yaml
      debug-resource-types: |
        [
          "ipams.aws.hops.ops.com.ai"
        ]

  publish:
    needs:
      - validate
      - test
    uses: unbounded-tech/workflows-crossplane/.github/workflows/publish.yaml@v2.5.1
    secrets: inherit
    with:
      tag: pr-${{ github.event.pull_request.number }}-${{ github.sha }}
